### ISSUE TITLE
Use title of one of the notes for the new combined note

### ISSUE THREAD

**Issue by chevdor** [JackGruber/joplin-plugin-combine-notes#7]
Arguably, using one of the note instead of the other may not be optimal but the chances it is better than the generic `Combined note` are quick good so I think it would be an option worth investigating.

Do you foresee any issue implementing this ?

A good bet IMO would be using the title of the most recently updated note.

**Comment by JackGruber** [comment]
I think I will make this configurable, that the first selected note name will be used.

**Comment by djsudduth** [comment]
Please add this! Your plug-in is one of the most useful ones I use. I typically create drafts and bibliographies by combining notes which makes your plug-in my most used. But, having all the titles mixed in makes me have to manually go in and remove them all.

@JackGruber are you keeping this plugin active or have you abandoned it?  I can do the change and create a pull request if you want.
PS - if I do a fork and pull request should I pull from the master or develop branch?
