### ISSUE TITLE
Remove individual titles within note text body when combining

### ISSUE THREAD

**Issue by djsudduth** [JackGruber/joplin-plugin-combine-notes#9]
Thank you @JackGruber for making the recent change. But, besides the custom title (which is awesome) - I also needed an option to remove each individual title from the combined note body. That's where I have to do all the work for a bibliography of 50-100 notes and have to go back into the combined note to remove all the titles embedded within the body.

**Comment by djsudduth** [comment]
@JackGruber - I tried to setup my dev environment and run the nvm, npm and node setup. But my `npm inst` fails in my joplin-plugin-combine-notes dev folder. Do I have to setup a full joplin dev environment as well? Or, can I just build the plugin and copy the build into my current Joplin install directory to test it?  Is there a specific version of Node I should be using - I have v20.9.0? (I'm not a javacript developer - mostly Python and Java)

**Comment by djsudduth** [comment]
@JackGruber - I've made the changes to have an option to remove the titles from the text body when combined. It seems to work fine in my testing. I did my best to also translate the settings text to German as well using Google Translate - you may need to tweak it. I will do a pull request against `develop`.  I also didn't do any versioning/version numbering.

**Comment by djsudduth** [comment]
Pull request to develop #10 done

**Comment by JackGruber** [comment]
Added in https://github.com/JackGruber/joplin-plugin-combine-notes/commit/046e228d6bde75676a1048360ad1a8201faa012d
